---
title: "Lectures"
output:
  html_document:
    includes:
      before_body: ../include/nav.html
      after_body: ../include/nothing.html
---


```{r include = FALSE}
library(dplyr)
library(stringr)
```

```{r include = FALSE}
# Import schedule
rawdat <- read.csv(file.path("../course-admin", "schedule_2020.csv"), stringsAsFactors = FALSE, colClasses = list(course = 'factor', dow = 'factor'))
rawdat$course <- as.factor(rawdat$course)

# Class meetings
rawdat_cm <- rawdat[rawdat$course == "STAT540",]

cdat <- rawdat_cm %>%
  mutate(ugly_date = ISOdate(2020, match(month, month.name), day),
         date = sprintf("%s-%02d %s",
                        months(ugly_date, abbreviate = TRUE),
                        day, dow),
         notes = ifelse(grepl("^lect", lect) & raw_notes != "",
                        sprintf("%s: %s", lect, raw_notes), raw_notes))
cdat %>% head(3)

## link to the class page of any class meetings where such exists
cmdat <-
  data.frame(pdf = list.files(path="../lectures/lectures_2020", pattern = '^lect.*pdf', full.names=TRUE),
             stringsAsFactors = FALSE)
cmdath <-
  data.frame(html = list.files(path="../lectures/lectures_2020", pattern = '^lect.*html', full.names=TRUE),
             stringsAsFactors = FALSE)
cmdat <- cmdat %>% mutate(lect = str_extract(pdf, "lect[0-9]+"))
cmdat$lect <- sapply(cmdat$lect, str_replace, pattern="lect0*([0-9]+)", replacement="lecture-\\1")
cmdath <- cmdath %>% mutate(lect = str_extract(html, "lect[0-9]+"))
cmdath$lect <- sapply(cmdath$lect, str_replace, pattern="lect0*([0-9]+)", replacement="lecture-\\1")
cdat <- cdat %>% left_join(cmdat, by="lect")
cdat <- cdat %>% left_join(cmdath, by="lect")

pdf_exists <- Negate(is.na)(cdat$pdf)
html_exists <- Negate(is.na)(cdat$html)

# Insert placeholder link to notes 
cdat$notes[pdf_exists] <-
  str_replace(cdat$notes[which(pdf_exists)],
              "(lecture-[0-9]+)|(lecture-[1-9]+)", '<a href="LINK">\\1</a>')
# Replace placeholder "LINK" which pdf file names 
cdat$notes[pdf_exists] <- str_replace(cdat$notes[which(pdf_exists)], "LINK", cdat$pdf[which(pdf_exists)])

# Append notes field with link to html if it exists
cdat$notes[html_exists] <- paste0(cdat$notes[which(html_exists)], " [[html](", cdat$html[which(html_exists)], ")]")

# Insert MATLAB code link 
cdat$notes <- str_replace(cdat$notes, "MATLAB code", '[MATLAB code](https://github.com/STAT540-UBC/STAT540-UBC.github.io/blob/master/lectures/multipleTestingProblemMATLABCode.m)')


dat_cm <- cdat %>% split(cdat$course)
dat_cm <- lapply(dat_cm, 'rownames<-', NULL)
```


<!-- unholy hack to make following two tables less wide and the same wide -->
<style type="text/css">
table {
   max-width: 70%;
}
</style>

### Class meetings and schedule 

**Time** : Mon Wed 9:30 - 11am

**Location** : ESB 2012

**Supplemental Files**: Source files for lectures created using Rmarkdown can be found [here](https://github.com/STAT540-UBC/STAT540-UBC.github.io/tree/master/lectures/lectures_2020/source) 

```{r results = 'asis', echo = FALSE}
knitr::kable(dat_cm[["STAT540"]] %>% select(date, notes, instructor))
```
